package com.satyam.trading2.service;

import com.satyam.trading2.datamodel.SignalRecord;
import com.satyam.trading2.datamodel.TradeSignal;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import javax.annotation.PostConstruct;
import java.io.*;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.stream.Collectors;

/**
 * Service to track all buy signals generated by strategies
 * Records both executed and rejected signals with reasons
 * Persists to CSV for later analytics
 */
@Slf4j
@Service
public class SignalAnalyticsService {

    // ⚠️ MEMORY FIX: Only keep today's signals in memory, not entire history
    private final List<SignalRecord> todaySignalRecords = new CopyOnWriteArrayList<>();
    private final String SIGNAL_FILE = "/home/ec2-user/buy_signals.csv";

    // Statistics (in-memory for quick access)
    private final Map<String, Integer> executedCountByStrategy = new ConcurrentHashMap<>();
    private final Map<String, Integer> rejectedCountByStrategy = new ConcurrentHashMap<>();
    private final Map<String, Integer> rejectionReasonCounts = new ConcurrentHashMap<>();

    // Track today's start timestamp
    private volatile long todayStartTimestamp;
    
    /**
     * Record a buy signal (executed or rejected)
     */
    public synchronized void recordSignal(TradeSignal signal, boolean executed, String rejectionReason, double capitalRequired) {
        SignalRecord record = new SignalRecord(signal, executed, rejectionReason, capitalRequired);

        // ⚠️ MEMORY FIX: Only keep today's signals in memory
        if (record.getTimestamp() >= todayStartTimestamp) {
            todaySignalRecords.add(record);
        }

        // Update statistics
        String strategy = signal.getStrategyName();
        if (executed) {
            executedCountByStrategy.merge(strategy, 1, Integer::sum);
            log.info("✅ Signal EXECUTED: {} @ {} - {} ({})",
                signal.getSymbol(), signal.getEntryPrice(), signal.getReason(), strategy);
        } else {
            rejectedCountByStrategy.merge(strategy, 1, Integer::sum);
            if (rejectionReason != null) {
                rejectionReasonCounts.merge(rejectionReason, 1, Integer::sum);
            }
        }

        // Persist to file
        persistSignal(record);
    }
    
    /**
     * Persist a signal record to CSV file
     */
    private void persistSignal(SignalRecord record) {
        try (FileWriter fw = new FileWriter(SIGNAL_FILE, true)) {
            fw.write(record.toCsvLine() + "\n");
            fw.flush();
        } catch (IOException e) {
            log.error("❌ Error saving signal to {}: {}", SIGNAL_FILE, e.getMessage());
        }
    }
    
    /**
     * Load signal history from file on startup
     * ⚠️ MEMORY FIX: Only load today's signals + rebuild stats from entire history
     */
    @PostConstruct
    public void loadSignalHistory() {
        // Set today's start timestamp
        todayStartTimestamp = getTodayStartTimestamp();

        File file = new File(SIGNAL_FILE);
        if (!file.exists()) {
            log.info("📊 No existing signal history file found. Starting fresh.");
            // Create file with header
            try (FileWriter fw = new FileWriter(SIGNAL_FILE)) {
                fw.write("timestamp,symbol,strategy,entryPrice,stopLoss,target,quantity,reason,entryType,executed,rejectionReason,capitalRequired\n");
            } catch (IOException e) {
                log.error("❌ Error creating signal file: {}", e.getMessage());
            }
            return;
        }

        int totalCount = 0;
        int todayCount = 0;
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            boolean isHeader = true;

            while ((line = br.readLine()) != null) {
                if (isHeader) {
                    isHeader = false;
                    continue; // Skip header
                }

                SignalRecord record = SignalRecord.fromCsvLine(line);
                if (record != null) {
                    totalCount++;

                    // Only keep today's signals in memory
                    if (record.getTimestamp() >= todayStartTimestamp) {
                        todaySignalRecords.add(record);
                        todayCount++;
                    }

                    // Rebuild statistics from all records
                    String strategy = record.getStrategyName();
                    if (record.isExecuted()) {
                        executedCountByStrategy.merge(strategy, 1, Integer::sum);
                    } else {
                        rejectedCountByStrategy.merge(strategy, 1, Integer::sum);
                        if (record.getRejectionReason() != null) {
                            rejectionReasonCounts.merge(record.getRejectionReason(), 1, Integer::sum);
                        }
                    }
                }
            }

            log.info("✅ Loaded {} total signal records ({} from today kept in memory)", totalCount, todayCount);
            log.info("📊 Memory savings: {} historical signals not loaded", totalCount - todayCount);
            printStatistics();

        } catch (IOException e) {
            log.error("❌ Error loading signal history: {}", e.getMessage());
        }
    }
    
    /**
     * Get today's signal records only (memory-efficient)
     */
    public List<SignalRecord> getAllSignals() {
        return todaySignalRecords;
    }

    /**
     * Get signals for a specific symbol (today only)
     */
    public List<SignalRecord> getSignalsForSymbol(String symbol) {
        return todaySignalRecords.stream()
            .filter(s -> s.getSymbol().equals(symbol))
            .collect(Collectors.toList());
    }

    /**
     * Get signals for a specific strategy (today only)
     */
    public List<SignalRecord> getSignalsForStrategy(String strategy) {
        return todaySignalRecords.stream()
            .filter(s -> s.getStrategyName().equals(strategy))
            .collect(Collectors.toList());
    }
    
    /**
     * Get execution rate for a strategy (% of signals that got executed)
     */
    public double getExecutionRate(String strategy) {
        int executed = executedCountByStrategy.getOrDefault(strategy, 0);
        int rejected = rejectedCountByStrategy.getOrDefault(strategy, 0);
        int total = executed + rejected;
        
        return total > 0 ? (executed * 100.0 / total) : 0.0;
    }
    
    /**
     * Get top rejection reasons
     */
    public Map<String, Integer> getRejectionReasonCounts() {
        return rejectionReasonCounts;
    }
    
    /**
     * Print statistics to console
     */
    public void printStatistics() {
        log.info("\n" + "=".repeat(80));
        log.info("📊 BUY SIGNAL ANALYTICS");
        log.info("=".repeat(80));
        
        for (String strategy : executedCountByStrategy.keySet()) {
            int executed = executedCountByStrategy.getOrDefault(strategy, 0);
            int rejected = rejectedCountByStrategy.getOrDefault(strategy, 0);
            int total = executed + rejected;
            double executionRate = total > 0 ? (executed * 100.0 / total) : 0.0;
            
            log.info("📈 {}: {} executed, {} rejected, {:.1f}% execution rate", 
                strategy, executed, rejected, executionRate);
        }
        
        if (!rejectionReasonCounts.isEmpty()) {
            log.info("\n📉 Top Rejection Reasons:");
            rejectionReasonCounts.entrySet().stream()
                .sorted((e1, e2) -> e2.getValue().compareTo(e1.getValue()))
                .limit(10)
                .forEach(e -> log.info("  - {}: {} times", e.getKey(), e.getValue()));
        }
        
        log.info("=".repeat(80) + "\n");
    }
    
    /**
     * Get today's signal count (already filtered in memory)
     */
    public int getTodaySignalCount() {
        return todaySignalRecords.size();
    }

    /**
     * Get today's execution rate (already filtered in memory)
     */
    public double getTodayExecutionRate() {
        if (todaySignalRecords.isEmpty()) return 0.0;

        long executed = todaySignalRecords.stream().filter(SignalRecord::isExecuted).count();
        return (executed * 100.0) / todaySignalRecords.size();
    }

    private long getTodayStartTimestamp() {
        java.time.LocalDate today = java.time.LocalDate.now();
        return today.atStartOfDay(java.time.ZoneId.systemDefault()).toInstant().toEpochMilli();
    }

    /**
     * Clear old signals at start of new day (scheduled task)
     */
    @Scheduled(cron = "0 0 0 * * *") // Every midnight
    public void clearYesterdaySignals() {
        todayStartTimestamp = getTodayStartTimestamp();
        todaySignalRecords.clear();
        log.info("🧹 Cleared yesterday's signals from memory");
    }

    /**
     * Scheduled summary print every 15 minutes during market hours
     */
    @Scheduled(fixedDelay = 900000) // 15 minutes
    public void printScheduledSummary() {
        java.time.LocalTime now = java.time.LocalTime.now();
        java.time.DayOfWeek today = java.time.LocalDate.now().getDayOfWeek();

        // Only run during market hours on weekdays
        if (today == java.time.DayOfWeek.SATURDAY || today == java.time.DayOfWeek.SUNDAY) {
            return;
        }

        if (now.isBefore(java.time.LocalTime.of(9, 15)) || now.isAfter(java.time.LocalTime.of(15, 30))) {
            return;
        }

        int todaySignals = getTodaySignalCount();
        if (todaySignals > 0) {
            log.info("\n📊 Today's Signal Analytics: {} signals, {:.1f}% execution rate",
                todaySignals, getTodayExecutionRate());
            printStatistics();
        }
    }
}

