package com.satyam.trading2.datamodel;

import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * Record of a buy signal generated by a strategy
 * Tracks whether it was executed or rejected, and why
 */
@Data
@AllArgsConstructor
public class SignalRecord {
    
    private long timestamp;              // When signal was generated
    private String symbol;               // Stock symbol
    private String strategyName;         // Which strategy generated it
    private double entryPrice;           // Proposed entry price
    private double stopLoss;             // Proposed stop loss
    private double target;               // Proposed target
    private int quantity;                // Proposed quantity
    private String reason;               // Signal generation reason
    private EntryType entryType;         // Entry type (TOP_GAINER, TOP_LOSER, etc.)
    
    // Execution status
    private boolean executed;            // Was the signal executed?
    private String rejectionReason;      // Why was it rejected (if not executed)
    
    // Additional context
    private double capitalRequired;      // Capital needed for this signal
    
    public SignalRecord(TradeSignal signal, boolean executed, String rejectionReason, double capitalRequired) {
        this.timestamp = System.currentTimeMillis();
        this.symbol = signal.getSymbol();
        this.strategyName = signal.getStrategyName();
        this.entryPrice = signal.getEntryPrice();
        this.stopLoss = signal.getStopLoss();
        this.target = signal.getTarget();
        this.quantity = signal.getQuantity();
        this.reason = signal.getReason();
        this.entryType = signal.getEntryType();
        this.executed = executed;
        this.rejectionReason = rejectionReason;
        this.capitalRequired = capitalRequired;
    }
    
    /**
     * CSV format for persistence:
     * timestamp,symbol,strategy,entryPrice,stopLoss,target,quantity,reason,entryType,executed,rejectionReason,capitalRequired
     */
    public String toCsvLine() {
        return timestamp + "," +
               symbol + "," +
               strategyName + "," +
               entryPrice + "," +
               stopLoss + "," +
               target + "," +
               quantity + "," +
               "\"" + reason.replace("\"", "\"\"") + "\"" + "," +  // Quote and escape reason
               (entryType != null ? entryType : "UNKNOWN") + "," +
               executed + "," +
               (rejectionReason != null ? "\"" + rejectionReason.replace("\"", "\"\"") + "\"" : "") + "," +
               capitalRequired;
    }
    
    /**
     * Parse from CSV line
     */
    public static SignalRecord fromCsvLine(String line) {
        // Handle quoted fields with commas
        String[] parts = parseCSVLine(line);
        
        if (parts.length < 12) {
            return null;
        }
        
        long timestamp = Long.parseLong(parts[0]);
        String symbol = parts[1];
        String strategyName = parts[2];
        double entryPrice = Double.parseDouble(parts[3]);
        double stopLoss = Double.parseDouble(parts[4]);
        double target = Double.parseDouble(parts[5]);
        int quantity = Integer.parseInt(parts[6]);
        String reason = parts[7];
        EntryType entryType = parts[8].isEmpty() ? EntryType.UNKNOWN : EntryType.valueOf(parts[8]);
        boolean executed = Boolean.parseBoolean(parts[9]);
        String rejectionReason = parts[10].isEmpty() ? null : parts[10];
        double capitalRequired = Double.parseDouble(parts[11]);
        
        return new SignalRecord(
            timestamp, symbol, strategyName, entryPrice, stopLoss, target,
            quantity, reason, entryType, executed, rejectionReason, capitalRequired
        );
    }
    
    /**
     * Simple CSV parser that handles quoted fields
     */
    private static String[] parseCSVLine(String line) {
        java.util.List<String> result = new java.util.ArrayList<>();
        boolean inQuotes = false;
        StringBuilder field = new StringBuilder();
        
        for (int i = 0; i < line.length(); i++) {
            char c = line.charAt(i);
            
            if (c == '"') {
                inQuotes = !inQuotes;
            } else if (c == ',' && !inQuotes) {
                result.add(field.toString());
                field = new StringBuilder();
            } else {
                field.append(c);
            }
        }
        result.add(field.toString());
        
        return result.toArray(new String[0]);
    }
}

